### ISSUE TITLE
COMException in HtmlControl

### ISSUE THREAD

**Issue by ryanwoodings** [metageek-llc/inSSIDer-2#15]
[Message]
The requested resource is in use. (Exception from HRESULT: 0x800700AA)

[Version]
2.0.2.1005

[WinVer]
Microsoft Windows NT 5.1.2600 Service Pack 3

[Platform]
x86

[StackTrace]
System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (Exception from HRESULT: 0x800700AA)
  at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.Navigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
  at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
  at System.Windows.Forms.WebBrowser.PerformNavigateHelper(String urlString, Boolean newWindow, String targetFrameName, Byte[] postData, String headers)
  at System.Windows.Forms.WebBrowser.Navigate(String urlString)
  at inSSIDer.HTML.HtmlControl.<UpdateFile>b__0(Object s, RunWorkerCompletedEventArgs e)
  at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
  at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by ryanwoodings** [comment]
This exception isn't even listed for WebBrowser.Navigate(String). It appears to be an XP issue.

**Comment by ryanwoodings** [comment]
Discussion of similar exception on StackOverflow: http://stackoverflow.com/questions/2230982/webbrowser-navigate-throws-comexception
