### ISSUE TITLE
NullReferenceException in NetworkInterfaceSelector.UpdateInterfaceList()

### ISSUE THREAD

**Issue by ryanwoodings** [metageek-llc/inSSIDer-2#17]
[Message]
Object reference not set to an instance of an object.

[Version]
2.0.3.1012

[WinVer]
Microsoft Windows NT 6.0.6000.0

[Platform]
x86

[StackTrace]
System.NullReferenceException: Object reference not set to an instance of an
object.
  at inSSIDer.UI.Controls.NetworkInterfaceSelector.UpdateInterfaceList()
  at inSSIDer.UI.Controls.NetworkInterfaceSelector.Initialize(ScannerN&
scanner)
  at inSSIDer.UI.Forms.FormMain.Initalize(ScannerN& scanner)
  at inSSIDer.Program.Main(String[] args)

**Comment by ryanwoodings** [comment]
Fixed in 2.0.6
