### ISSUE TITLE
2.0.5.1111 crashes on exit.

### ISSUE THREAD

**Issue by metageektrent** [metageek-llc/inSSIDer-2#27]
This on closing down on( Win 7) after using program succesfully.
[Message]
Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

[Version]
2.0.5.1111

[WinVer]
Microsoft Windows NT 6.1.7600.0

[Platform]
x86

[StackTrace]
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at System.Windows.Forms.Control.Invoke(Delegate method)
at inSSIDer.UI.Mini.ScannerViewMini.Go() in MetaScanner\UI\Mini\ScannerViewMini.cs:line 125
at inSSIDer.UI.Mini.FormMini.RefreshAll() in MetaScanner\UI\Mini\frmMini.cs:line 140
at inSSIDer.UI.Mini.FormMini.ScannerScanComplete(Object sender, ScanCompleteEventArgs e) in MetaScanner\UI\Mini\frmMini.cs:line 127
at inSSIDer.Scanning.ScanController.OnScanComplete(NetworkData[] data, GpsData gpsData) in MetaScanner\Scanning\ScanController.cs:line 153
at inSSIDer.Scanning.ScanController.NetworkScannerNewNetworkDataEvent(Object sender, IncomingDataEventArgs`1 e) in MetaScanner\Scanning\ScanController.cs:line 118
at inSSIDer.Scanning.NetworkScannerN.OnNewNetworkData(IEnumerable`1 data) in MetaScanner\Scanning\NetworkScannerN.cs:line 193
at inSSIDer.Scanning.NetworkScannerN.ScanThreadFunc() in MetaScanner\Scanning\NetworkScannerN.cs:line 176
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by TylerAdkisson** [comment]
This should be fixed in 2.0.7.
